# Generated by Django 4.2.11 on 2024-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_process_queue_alter_process_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип работы')),
                ('process', models.ManyToManyField(to='production.process', verbose_name='Процесс')),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работы',
            },
        ),
    ]
