# Generated by Django 4.2.11 on 2024-06-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_typework'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxmodel',
            name='additional_properties',
            field=models.IntegerField(blank=True, choices=[(1, 'Влагостойкость'), (2, 'Устойчивость к воздействию'), (3, 'Экологичность'), (4, 'Теплоизоляция'), (5, 'Антистатические свойства')], null=True, verbose_name='Дополнительные свойства'),
        ),
        migrations.AddField(
            model_name='boxmodel',
            name='closure_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Склейка'), (2, 'Клапаны'), (3, 'Автозамок'), (4, 'Скобы'), (5, 'Ленты или бандероли'), (6, 'Крючки или зажимы'), (7, 'Вкладыш'), (8, 'Магниты')], null=True, verbose_name='Тип замыкания'),
        ),
        migrations.AddField(
            model_name='boxmodel',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='boxmodel',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='boxmodel',
            name='grams_per_box',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Грамм на одну коробку'),
        ),
        migrations.AddField(
            model_name='boxmodel',
            name='max_load',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Максимальная нагрузка'),
        ),
    ]
