# Generated by Django 4.2.11 on 2024-06-19 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_materialtype_queue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0004_boxmodel_additional_properties_boxmodel_closure_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='packed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество упаковано'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.firm', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.specification', verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='type_order',
            field=models.CharField(choices=[('Образец', 'Образец'), ('Экспорт', 'Экспорт'), ('Внутренный рынок', 'Внутренный рынок'), ('Услуга', 'Услуга')], max_length=100, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='shipping_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('ЗАКОНЧЕНО', 'ЗАКОНЧЕНО'), ('НОВАЯ', 'НОВАЯ'), ('Упаковано', 'Упаковано')], default='НОВАЯ', max_length=20, verbose_name='Статус'),
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='type_of_work',
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Временная метка')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.process', verbose_name='Процесс')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_logs', to='production.productionorder', verbose_name='Заказ на производство')),
            ],
            options={
                'verbose_name': 'Процесс производства',
                'verbose_name_plural': 'Процессы производства',
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='type_of_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.typework', verbose_name='Тип Работы'),
        ),
    ]
