# Generated by Django 4.2.11 on 2024-06-21 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_boxorderdetail_box_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxmodel',
            name='grams_per_box',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Грамм на одну коробку'),
        ),
    ]
