# Generated by Django 4.2.11 on 2024-06-24 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0009_remove_outgoingmaterial_production_order'),
        ('production', '0007_alter_boxmodel_grams_per_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='incoming_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order', to='depo.incomingmaterial', verbose_name='Детали входящего'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='outgoing_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order', to='depo.outgoingmaterial', verbose_name='Детали исходящего'),
        ),
    ]
