# Generated by Django 4.2.11 on 2024-06-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0010_remove_outgoing_production_order_and_more'),
        ('production', '0009_alter_productionorder_incoming_detail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typework',
            options={'verbose_name': 'Вид работы', 'verbose_name_plural': 'Виды работы'},
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='incoming_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_detail_production_order', to='depo.incomingmaterial', verbose_name='Детали прихода'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='outgoing_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_detail_production_order', to='depo.outgoingmaterial', verbose_name='Детали расхода'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='type_of_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.typework', verbose_name='Вид Работы'),
        ),
    ]
