# Generated by Django 4.2.11 on 2024-04-23 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("depo", "0002_initial"),
        ("info", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="outgoing",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="outgoing",
            name="to_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_to_warehouse",
                to="info.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="outgoing",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="outgoing",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_warehouse",
                to="info.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="incomingmaterial",
            name="incoming",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="depo.incoming"
            ),
        ),
        migrations.AddField(
            model_name="incomingmaterial",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="info.material"
            ),
        ),
        migrations.AddField(
            model_name="incoming",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incoming",
            name="from_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_from_warehouse",
                to="info.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="incoming",
            name="outgoing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="depo.outgoing",
            ),
        ),
        migrations.AddField(
            model_name="incoming",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incoming",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_warehouse",
                to="info.warehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["material"], name="depo_stock_materia_8a9e23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outgoing",
            index=models.Index(fields=["code"], name="depo_outgoi_code_98c757_idx"),
        ),
        migrations.AddIndex(
            model_name="incoming",
            index=models.Index(
                fields=["warehouse", "from_warehouse"],
                name="depo_incomi_warehou_6fe2e3_idx",
            ),
        ),
    ]
