# Generated by Django 4.2.11 on 2024-06-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_boxmodel_grams_per_box'),
        ('depo', '0007_alter_stock_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmaterial',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_materials', to='production.productionorder'),
        ),
    ]
