# Generated by Django 4.2.11 on 2024-06-24 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_productionorder_incoming_detail_and_more'),
        ('depo', '0009_remove_outgoingmaterial_production_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoing',
            name='production_order',
        ),
        migrations.AddField(
            model_name='incomingmaterial',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_materials_set', to='production.productionorder'),
        ),
        migrations.AddField(
            model_name='outgoingmaterial',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_materials_set', to='production.productionorder'),
        ),
    ]
