# Generated by Django 4.2.11 on 2024-04-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-created_time"],
                "abstract": False,
            },
        ),
    ]
