# Generated by Django 4.2.11 on 2024-04-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoxSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("width", models.PositiveIntegerField(verbose_name="Ширина")),
                ("height", models.PositiveIntegerField(verbose_name="Высота")),
                ("length", models.PositiveIntegerField(verbose_name="Длина")),
            ],
            options={
                "verbose_name": "Размер коробки",
                "verbose_name_plural": "Размеры коробок",
            },
        ),
        migrations.CreateModel(
            name="BoxType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тип коробки",
                "verbose_name_plural": "Типы коробок",
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
            },
        ),
        migrations.CreateModel(
            name="Firm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "type_firm",
                    models.CharField(
                        choices=[
                            ("supplier", "Поставщик"),
                            ("customer", "Заказчик"),
                            ("both", "Поставщик и Заказчик"),
                        ],
                        max_length=20,
                        verbose_name="Тип фирмы",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Активна"
                    ),
                ),
                (
                    "legal_address",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Юридический адрес",
                    ),
                ),
                (
                    "actual_address",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Фактический адрес",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Номер лицензии",
                    ),
                ),
                (
                    "mfo",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="МФО"
                    ),
                ),
            ],
            options={
                "verbose_name": "Фирма",
                "verbose_name_plural": "Фирмы",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="Код"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "material_thickness",
                    models.FloatField(verbose_name="Толщина материала"),
                ),
                (
                    "unit_of_measurement",
                    models.CharField(
                        choices=[
                            ("sht", "шт"),
                            ("sm", "см"),
                            ("mm", "мм"),
                            ("kg", "кг"),
                            ("litr", "л"),
                        ],
                        default=None,
                        max_length=10,
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
            },
        ),
        migrations.CreateModel(
            name="MaterialGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Группа материалов",
                "verbose_name_plural": "Группы материалов",
            },
        ),
        migrations.CreateModel(
            name="MaterialSpecialGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Специальная группа материалов",
                "verbose_name_plural": "Специальные группы материалов",
            },
        ),
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тип материала",
                "verbose_name_plural": "Типы материалов",
            },
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("year", models.CharField(max_length=4, verbose_name="Год")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Спецификация",
                "verbose_name_plural": "Спецификации",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Местоположение",
                    ),
                ),
                (
                    "can_import",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        null=True,
                        verbose_name="Может импортировать",
                    ),
                ),
                (
                    "can_export",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Может экспортировать",
                    ),
                ),
                (
                    "use_negative",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Использовать отрицательные значения",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
            },
        ),
    ]
