# Generated by Django 4.2.11 on 2024-05-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_remove_material_material_thickness_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxsize",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Название"
            ),
        ),
    ]
