# Generated by Django 4.2.11 on 2024-05-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0004_alter_boxsize_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialtype",
            name="queue",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="Очеред"
            ),
        ),
    ]
