# Generated by Django 4.2.11 on 2024-06-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_boxsize_created_by_boxsize_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_thickness',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Плотность(Г/м2)'),
        ),
    ]
