# Generated by Django 4.2.11 on 2024-06-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_material_material_thickness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='material_thickness',
        ),
    ]
