# Generated by Django 4.2.11 on 2024-06-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_remove_material_material_thickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='Плотность(Г/м2)'),
        ),
    ]
